version: "3.8"
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: zkml-client:1.0
    hostname: zkml-client
    networks:
      - mynet
    command: cargo run --bin server 3
    environment:
      - RUSTFLAGS=-Awarnings
    ports:
      - "4000:4000"
    container_name: server
    volumes:
      - ./log:/app/log
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G

  client:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: zkml-client:1.0
    hostname: zkml-client
    networks:
      - mynet
    links:
      - server
    command: cargo run --bin client server:4000 1
    environment:
      - RUSTFLAGS=-Awarnings
    depends_on:
      - server
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "1.0"
          memory: 2G

networks:
  mynet:
    driver: bridge
